### ISSUE TITLE
参数类型不匹配

### ISSUE THREAD

**Issue by aozima** [XradioTech/XR871#1]
xr871sdk/src/driver/chip/hal_ccm.c:72:

`void HAL_CCM_BusEnablePeriphClock(CCM_BusPeriphBit periphMask)`

xr871sdk/include/driver/chip/hal_ccm.h:231:

`void HAL_CCM_BusEnablePeriphClock(uint32_t periphMask)`

**Comment by Aaron-Ye** [comment]
We will fix it up in next commit, thanks

**Comment by aozima** [comment]
03_SDK\xr871sdk\include\driver\chip\hal_efuse.h L48

`	__IO uint32_t DEBUG;			/* 0x0094 EFUSE debug register					*/
`
与编译时 03_SDK\xr871sdk\gcc.mk L55 定义的

`  OPTIMIZE_FLAG :=  -O0 -DDEBUG`

是冲突的，需要修正

类似的，在其它地方也有多个 叫  DEBUG 的变量名称

**Comment by Aaron-Ye** [comment]
已处理
