### ISSUE TITLE
How to write firmware onto the XR871_EVB_MAIN_BRD_V_1_1 using Linux?

### ISSUE THREAD

**Issue by master-q** [XradioTech/XR871#2]
How to write firmware onto the XR871_EVB_MAIN_BRD_V_1_1 using Linux?

Following document explains how to build firmware on both Windows and Linux:

https://github.com/XradioTech/XR871/blob/master/03_SDK/XR871_Quick_Start_Guide-CN.pdf

But the document doesn't write the firmware using Linux. May I use https://www.segger.com/downloads/jlink to write the firmware?

**Comment by master-q** [comment]
And where can I get the PhoenixMC software for Windows?

**Comment by Aaron-Ye** [comment]
we will upload the linux version of PhoenixMC

**Comment by Aaron-Ye** [comment]
we upload the linux phoenixmc: 

https://github.com/XradioTech/XR871/tree/master/03_SDK/xr871sdk/tools

and the user guide please refer to 

https://github.com/XradioTech/XR871/blob/master/03_SDK/XR871_phoenixMC_u_User_Guide-CN.pdf

thank you

**Comment by master-q** [comment]
Thanks a lot. I'll try it.
