### ISSUE TITLE
xr871SDk的src/net下已经有编译好的paho.mqtt.embedded-c，具体该怎么调用使用呢？ 

### ISSUE THREAD

**Issue by mmabluesky** [XradioTech/XR871#6]
xr871SDk的src/net下已经有编译好的paho.mqtt.embedded-c， 我试着仿照paho.mqtt.embedded-c下的sample，编写一个mqtt demo，但在xr871上一直运行不起来，socket方面估计要移植更改下 ，能给些指导性意见吗

**Comment by mmabluesky** [comment]
已解决

**Comment by Aaron-Ye** [comment]
不好意思，之前设置有问题，没收到邮件，如有疑问请在提出，谢谢

**Comment by mmabluesky** [comment]
@Aaron-Ye  emm ，没事了，已经没搞这块了，之前只是想编写个mqtt demo ，让xr871连接上百度天工，
